name: NicePM
main: com.joshargent.NicePM.NicePM
version: 1.0.0
commands:
  tell:
    description: Sends a private message to a player
    usage: /<command> <player> <message>
    aliases: [msg]
  reply:
    description: Reply to a private message
    usage: /<command> <message>
    aliases: [r]